[tool.semantic_release]
branch = "main"
version_source = "tag"
commit_message = "chore(release): {version} [skip ci]"
changelog_file = "CHANGELOG.md"
version_variable = "VERSION"
upload_to_pypi = false
